version: '2'
services:
  db:
    image: ibmcom/cloudant-developer:latest
    ports:  
      - "30080:80"
    hostname: cloudant
    network_mode: bridge
  web:
    image: markwatsonatx/tutorial-polymer-shop-hoodie:latest
    volumes:
      - ./src/app:/usr/src/app
    working_dir: /usr/src/app
    command: /usr/src/app/startup.sh
    ports:
      - "38080:8080"
    links:
      - db
    network_mode: bridge
